services:
  nginx:
    image: nginx:latest
    ports:
      # - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/nginx.conf
      - ./html:/usr/share/nginx/html
      - /var/opt/pve-vm/server-cert/server.crt:/server.crt:ro
      - /var/opt/pve-vm/server-cert/server.key:/server.key:ro